### ISSUE TITLE
On cell event not assigned

### ISSUE THREAD

**Issue by fredvs** [rchastain/msegui-chessboard#2]
Hello Roland.
I am **very** impressed how fast you catch the mse way.
Super your rules-added, it works perfectly.

I have seen that `grid.oncellevent()` is no more assigned.
Is it wanted?
Because it is needed to use the keyboard and to have more control.
The original method of Martin `oncellev()` has only keyboard events implemented.
But Mouse events are very easy to implement too (see my previous zip).

Fre;D

**Comment by fredvs** [comment]
Here how to easy assign a method with msegui designer.
Click on the grid, the `Object inspector` will appear.
Then, at bottom, on row  `oncellevent` add a name for the method.
For example `oncellev` and press Enter.
This will create automatically the code of the method for you.
And if you 2xclick now on `oncellev` in  `Object inspector`, it will bring you in the source editor, at the right place to write your code.

See picture:
![oncellev](https://user-images.githubusercontent.com/3421249/74114222-00036480-4ba9-11ea-897b-98088b221ec0.png)

Fre;D

**Comment by rchastain** [comment]
Hello Fred!
Thank you for taking a look at my work and writing your messages. The _oncellev_ method is missing because I started from the first version of the example. I hadn't noticed that difference between the two versions.
I will add the method. Thank you for the explanation about Object Inspector.
Regards.
Roland

**Comment by rchastain** [comment]
There are too much differences between the two versions of the example. I think I will restart from the latest version.

**Comment by fredvs** [comment]
Hello Roland.
Huh, about what "two versions" are you talking?
I did take the demo from here:
https://github.com/mse-org/mseuniverse/tree/master/samples/widgets/grids/chessboard

**Comment by rchastain** [comment]
Hello Fred!

Martin made a first version of the example, without texture and without keyboard management, and later he updated his example. But I still have the first version on my hard disk. I started from that first version.
I think I will open another repository, starting from the second version of the example.

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

Ha ok.
I did check the last commit Martin did for his chessboard demo.
It was Nov 1, 2018, so few days before to go.
I am sure he is very happy that you continue your both-work.

Fre;D

**Comment by rchastain** [comment]
I hope that Martin is happy that _we_ continue his work. ;)

**Comment by rchastain** [comment]
I am looking at the commits. Very instructive.

But I see now that it wasn't a good idea to start from the "old version". In fact there are not only two versions. The final version has many differences with the first, not only keyboard and textures.

**Comment by fredvs** [comment]
Hello Roland.
Yep, I just see that he did add some properties for grids for that last commits of chessboard...
Good night!

**Comment by rchastain** [comment]
I restart from latest code written by Martin. It isn't a good idea to keep the old code.

Good night Fred!
